(()=>{
const C=window.HISTORY_CONTENT,CFG=window.HISTORY_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const browserTts=CFG.browserTts||{},didAgent=CFG.didAgent||{},speechEngine=window.speechSynthesis||null;
let mode='theory',topic=null,index=0,queue=[],answers=[],voiceOn=didAgent.enabled!==false||browserTts.enabled!==false&&Boolean(speechEngine&&window.SpeechSynthesisUtterance),recognition=null,mediaRecorder=null,audioChunks=[],micStream=null,cameraStream=null,micEnabled=true,videoHidden=false,awaitingFollowUp=false,pendingAnswer=null,revisitQuestion=null,sessionHistory=[],lastPeterText='';
let sessionContext={asked:[],mistakes:[],hints:[],lastQuestion:null,previousQuestion:null,lastAnswer:null,lastFeedback:null,offTopicCount:0};
let conversationState='IDLE',recognitionEpoch=0,speechEpoch=0,currentUtterance=null,speechResolve=null,selectedVoice=null,autoListenArmed=false,listenResumeTimer=null,didApi=null,didReady=false,didSpeaking=false,didSpeechResolve=null,didSubscriptions=[],lessonActive=false,didMountObserver=null;
const screens=$$('.screen');
function ensureVoiceUi(){const actions=$('.top-actions');if(actions&&!$('#voiceQuality')){const badge=document.createElement('span');badge.id='voiceQuality';badge.className='voice-quality neural';badge.textContent=didAgent.enabled!==false?'D-ID Agent · подключение':voiceOn?'Системный голос · резерв':'Озвучка недоступна';actions.prepend?.(badge)}const toggle=$('#voiceToggle');if(toggle){toggle.textContent=voiceOn?'🔊':'🔇';toggle.title=voiceOn?'Голос включён':'Голос выключен'}}
ensureVoiceUi();
function waitForDidApi(timeout=9000){return new Promise((resolve,reject)=>{if(window.DID_AGENTS_API)return resolve(window.DID_AGENTS_API);const started=Date.now(),timer=setInterval(()=>{if(window.DID_AGENTS_API){clearInterval(timer);resolve(window.DID_AGENTS_API)}else if(Date.now()-started>=timeout){clearInterval(timer);reject(Error('did-timeout'))}},100)})}
function mountDidWidget(){const target=$('#didAgentContainer'),widget=document.querySelector('.didagent_target');if(!target||!widget)return false;if(widget.parentElement!==target)target.append(widget);target.classList.add('did-mounted');$('#didAgentFallback')?.classList.add('hidden');didMountObserver?.disconnect?.();didMountObserver=null;return true}
function watchDidWidget(){if(mountDidWidget())return;if(window.MutationObserver&&!didMountObserver){didMountObserver=new window.MutationObserver(()=>mountDidWidget());didMountObserver.observe(document.body,{childList:true,subtree:true})}let attempts=0;const timer=setInterval(()=>{attempts++;if(mountDidWidget()||attempts>=100)clearInterval(timer)},100)}
function loadDidEmbed(){
  if(didAgent.enabled===false||document.querySelector('script[data-name="did-agent"]'))return;
  const target=$('#didAgentContainer');
  if(!target)return;
  const script=document.createElement('script');
  script.type='module';
  script.src='https://agent.d-id.com/v2/index.js';
  script.setAttribute('data-mode','full');
  script.setAttribute('data-client-key',didAgent.clientKey||'ck_N3omtzg6w_CASkFECrjPa');
  script.setAttribute('data-agent-id',didAgent.agentId||'v2_agt_HUTMZ9e7');
  script.setAttribute('data-name','did-agent');
  script.setAttribute('data-monitor','true');
  script.setAttribute('data-light-mode','false');
  script.setAttribute('data-target-id','didAgentContainer');
  watchDidWidget();
  document.body.append(script);
}
async function initDidAgent(){if(didAgent.enabled===false)return false;loadDidEmbed();try{didApi=await waitForDidApi();didApi.configure?.({showChatToggle:false,showMicToggle:false,showRestartButton:false,openMode:lessonActive?'expanded':'compact'});await didApi.functions?.toggleMicState?.(true);didSubscriptions.push(didApi.events.on('connection',({state})=>{if(state==='connected'){didReady=true;$('#didAgentFallback')?.classList.add('hidden');voiceBadge('D-ID · живой голос и lip-sync',true);if(conversationState==='IDLE')avatarState('idle')}else if(['fail','closed'].includes(state)){didReady=false;if(!mountDidWidget())$('#didAgentFallback')?.classList.remove('hidden');voiceBadge('D-ID ожидает подключения')}}));didSubscriptions.push(didApi.events.on('agentActivity',({state})=>{if(state==='TALKING'){didSpeaking=true;hardStopSpeechInput();setConversationState('SPEAKING');avatarState('speaking')}else if(state==='LOADING'||state==='BUFFERING'){hardStopSpeechInput();setConversationState('PROCESSING')}else if(state==='IDLE'&&didSpeaking){didSpeaking=false;didSpeechResolve?.(true)}}));didSubscriptions.push(didApi.events.on('error',()=>{didReady=false;didSpeaking=false;didSpeechResolve?.(false)}));return true}catch(e){didReady=false;if(mountDidWidget())voiceBadge('D-ID готов · нажмите Start call');else{$('#didAgentFallback')?.classList.remove('hidden');voiceBadge('D-ID недоступен · системный резерв')}return false}}
function setDidOpen(expanded){lessonActive=Boolean(expanded);document.body?.classList?.toggle('lesson-active',lessonActive);const api=didApi||window.DID_AGENTS_API;api?.configure?.({openMode:lessonActive?'expanded':'compact'});if(!lessonActive)return;loadDidEmbed();watchDidWidget();if(!didApi)initDidAgent()}
function pickRussianVoice(){if(!speechEngine)return null;const voices=speechEngine.getVoices?.()||[],russian=voices.filter(v=>/^ru(?:-|_)/i.test(v.lang)||/рус|russian/i.test(`${v.name} ${v.lang}`));const male=/(dmitry|pavel|yuri|nikolai|maxim|alex|aleks|vladimir|mikhail|дмитр|павел|юрий|никол|максим|алекс|владимир|михаил|male|муж)/i;selectedVoice=russian.find(v=>male.test(v.name))||russian[0]||null;if(didAgent.enabled===false)voiceBadge(selectedVoice?`Системный голос · ${selectedVoice.name}`:voiceOn?'Русская озвучка браузера':'Озвучка недоступна',voiceOn);return selectedVoice}
pickRussianVoice();
if(speechEngine?.addEventListener)speechEngine.addEventListener('voiceschanged',pickRussianVoice);else if(speechEngine)speechEngine.onvoiceschanged=pickRussianVoice;
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo({top:0,behavior:'smooth'})}
function avatarState(state){const labels={idle:'Пётр готов',listening:'Слушаю ваш ответ',thinking:'Пётр обдумывает ответ',voicing:'Пётр говорит',speaking:'Пётр говорит'};const el=$('#characterState');if(el){el.className=`character-state ${state}`;el.querySelector('span').textContent=labels[state]||labels.idle}$('#soundWave')?.classList.toggle('active',state==='speaking'||state==='voicing')}
function setConversationState(next){conversationState=next;const listening=next==='LISTENING',busy=next==='PROCESSING'||next==='SPEAKING';$('#micBtn').disabled=!micEnabled||busy;$('#micBtn').classList.toggle('listening',listening);$('#micBtn b').textContent=listening?'Слушаю вас…':'Ответить';$('#stopMicBtn').classList.toggle('hidden',!listening);if(next==='LISTENING'){avatarState('listening');setSystem('🎙 Слушаю вас…')}else if(next==='PROCESSING'){avatarState('thinking');setSystem('Пётр обдумывает ответ…')}else if(next==='SPEAKING'){avatarState('speaking');setSystem('🔊 Пётр говорит…')}else{avatarState('idle');setSystem('Нажмите «Ответить», чтобы включить микрофон.') }}
function hardStopSpeechInput(){clearTimeout(listenResumeTimer);listenResumeTimer=null;recognitionEpoch++;const active=recognition;recognition=null;if(active){active.onresult=null;active.onend=null;active.onerror=null;try{active.abort?.()}catch(e){try{active.stop?.()}catch(e2){}}}if(mediaRecorder?.state==='recording'){mediaRecorder.ondataavailable=null;mediaRecorder.onstop=null;try{mediaRecorder.stop()}catch(e){}}mediaRecorder=null;releaseMic();$('#micBtn').classList.remove('listening');$('#stopMicBtn').classList.add('hidden')}
function bubble(who,text,kind=''){const el=document.createElement('div');el.className=`bubble ${who} ${kind}`;el.innerHTML=`<small>${who==='student'?'ТЫ':'ПЁТР I'}</small>${escapeHtml(text)}`;$('#conversation').append(el);$('#conversation').scrollTop=$('#conversation').scrollHeight}
function setSystem(text,error=false){$('#systemMessage').textContent=text;$('#systemMessage').style.color=error?'#c52e5d':''}
function renderTopics(){const labels={theory:'ТЕОРИЯ',training:'ТРЕНИРОВКА',exam:'ЭКЗАМЕН'};$('#topicModeBadge').textContent=labels[mode];$('#topicInstruction').textContent=mode==='theory'?'Выбери тему и задавай Петру любые вопросы.':mode==='training'?'В каждой теме — 6 вопросов, подсказки и короткий разбор.':'В каждой теме — 6 заданий без подсказок. Результат появится в конце.';$('#topicGrid').innerHTML=C.topics.map(t=>`<button class="topic-card" data-topic="${t.id}"><span class="topic-no">${t.n}</span><h3>${t.title}</h3><p>${t.points.join(' · ')}</p><span class="topic-go">→</span></button>`).join('');$$('.topic-card').forEach(b=>b.onclick=()=>selectTopic(b.dataset.topic));show('topicScreen')}
function selectTopic(id){topic=C.topics.find(t=>t.id===id);const labels={theory:'ТЕОРИЯ',training:'ТРЕНИРОВКА',exam:'ЭКЗАМЕН'};$('#setupMode').textContent=labels[mode];$('#setupTitle').textContent=topic.title;$('#setupText').textContent=mode==='theory'?`${topic.intro} Можно задавать свободные вопросы текстом или голосом.`:mode==='training'?`Шесть заданий по теме. После ответа Пётр даст короткий разбор и при необходимости задаст уточняющий вопрос.`:`Шесть заданий по теме. Подсказок и промежуточных оценок не будет — полный разбор появится в конце.`;$('#examWarning').style.display=mode==='exam'?'flex':'none';show('setupScreen')}
async function begin(){index=0;answers=[];sessionHistory=[];sessionContext={asked:[],mistakes:[],hints:[],lastQuestion:null,previousQuestion:null,lastAnswer:null,lastFeedback:null,offTopicCount:0};awaitingFollowUp=false;pendingAnswer=null;revisitQuestion=null;queue=mode==='theory'?[]:shuffle([...C.questions[topic.id]]);$('#sessionMode').textContent={theory:'ТЕОРИЯ',training:'ТРЕНИРОВКА',exam:'ЭКЗАМЕН'}[mode];$('#sessionTopic').textContent=topic.title;$('#hintBtn').classList.toggle('hidden',mode==='exam'||mode==='theory');$('#conversation').innerHTML='';$('#answerInput').value='';$('#hintBox').classList.remove('show');show('sessionScreen');setDidOpen(true);setSystem(CFG.aiEndpoint?'Подключён ИИ-репетитор с памятью занятия.':'Локальный учебный режим: Пётр помнит разговор и различает ошибку, неполный ответ и уход от темы.');if(mode==='theory'){updateProgress();await peterSay(`${topic.intro} С чего начнём?`,'СВОБОДНЫЙ ДИАЛОГ')}else{renderQuestion()}}
function updateProgress(){if(mode==='theory'){$('#progressText').textContent='Свободный разговор';$('#progressBar').style.width='100%'}else{$('#progressText').textContent=`Вопрос ${Math.min(index+1,6)} из 6`;$('#progressBar').style.width=`${Math.min(100,(index/6)*100)}%`}}
function variedQuestion(q){const variants=[q.q,`Ответь своими словами: ${q.q.charAt(0).toLowerCase()+q.q.slice(1)}`,`Раскрой смысл задания: ${q.q.charAt(0).toLowerCase()+q.q.slice(1)}`];return variants[(index+sessionContext.asked.length)%variants.length]}
async function renderQuestion(){awaitingFollowUp=false;pendingAnswer=null;$('#hintBox').classList.remove('show');$('#answerInput').value='';const q=queue[index];if(!q){finishSession();return}sessionContext.previousQuestion=sessionContext.lastQuestion;sessionContext.lastQuestion=q;const spoken=variedQuestion(q);sessionContext.asked.push(spoken);updateProgress();await peterSay(spoken,q.type);$('#sendBtn').innerHTML=index===5?'Завершить <span>→</span>':'Отправить <span>→</span>'}
async function peterSay(text,type){hardStopSpeechInput();setConversationState('PROCESSING');lastPeterText=text;$('#questionType').textContent=type||'ОТВЕТ ПЕТРА';bubble('peter',text);sessionHistory.push({role:'assistant',content:text});const spoken=await speak(text);setConversationState('IDLE');if(spoken)scheduleListeningResume()}
function voiceBadge(text,neural=false){const badge=$('#voiceQuality');if(badge){badge.textContent=text;badge.classList.toggle('neural',neural)}}
async function speakWithDid(text){if(!didApi)await initDidAgent();if(!didApi?.functions?.speak)throw Error('did-unavailable');hardStopSpeechInput();const token=++speechEpoch;await didApi.functions.toggleMicState?.(true);setConversationState('SPEAKING');avatarState('speaking');$('#stopSpeechBtn')?.classList.remove('hidden');voiceBadge('D-ID · живой голос и lip-sync',true);const activity=new Promise(resolve=>{let settled=false;const finish=value=>{if(settled)return;settled=true;didSpeechResolve=null;resolve(value)};didSpeechResolve=finish;setTimeout(()=>finish(false),Math.max(15000,String(text).length*135))});try{await didApi.functions.speak({type:'text',input:text});const played=await activity;if(token!==speechEpoch)return false;return played||didReady}catch(e){didSpeechResolve?.(false);throw e}finally{if(token===speechEpoch){didSpeaking=false;didSpeechResolve=null;$('#stopSpeechBtn')?.classList.add('hidden')}}}
function cancelPeterSpeech(resume=false){speechEpoch++;try{didApi?.functions?.interrupt?.()}catch(e){}try{didApi?.functions?.toggleMicState?.(true)}catch(e){}didSpeaking=false;const didDone=didSpeechResolve;didSpeechResolve=null;didDone?.(false);try{speechEngine?.cancel()}catch(e){}currentUtterance=null;const done=speechResolve;speechResolve=null;done?.(false);$('#stopSpeechBtn')?.classList.add('hidden');if(conversationState==='SPEAKING'||conversationState==='PROCESSING')setConversationState('IDLE');if(resume)scheduleListeningResume()}
function scheduleListeningResume(){clearTimeout(listenResumeTimer);if(!autoListenArmed||!micEnabled)return;listenResumeTimer=setTimeout(()=>{listenResumeTimer=null;if(conversationState==='IDLE')startListening()},700)}
async function speak(text){if(!voiceOn)return false;hardStopSpeechInput();cancelPeterSpeech(false);if(didAgent.enabled!==false){try{return await speakWithDid(text)}catch(e){if(mountDidWidget()){voiceBadge('D-ID · используется выбранный голос агента');setSystem('Нажмите зелёную кнопку звонка на Петре, чтобы включить выбранный голос D-ID.');return false}voiceBadge('D-ID временно недоступен');$('#didAgentFallback')?.classList.remove('hidden')}}if(browserTts.enabled===false){setSystem('Озвучка D-ID временно недоступна. Текстовый диалог продолжает работать.',true);return false}if(!speechEngine||!window.SpeechSynthesisUtterance){setSystem('Живой аватар временно недоступен. Текстовый диалог продолжает работать.',true);return false}const token=++speechEpoch,utterance=new window.SpeechSynthesisUtterance(text);currentUtterance=utterance;utterance.lang=browserTts.lang||'ru-RU';utterance.rate=Number(browserTts.rate)||0.9;utterance.pitch=Number(browserTts.pitch)||0.85;utterance.volume=1;if(!selectedVoice)pickRussianVoice();if(selectedVoice)utterance.voice=selectedVoice;avatarState('voicing');setConversationState('SPEAKING');$('#stopSpeechBtn')?.classList.remove('hidden');voiceBadge(selectedVoice?`Системный резерв · ${selectedVoice.name}`:'Системный голос · резерв');return await new Promise(resolve=>{let settled=false;const finish=played=>{if(settled)return;settled=true;if(token===speechEpoch){currentUtterance=null;speechResolve=null;$('#stopSpeechBtn')?.classList.add('hidden')}resolve(played)};speechResolve=finish;utterance.onend=()=>finish(true);utterance.onerror=()=>{setSystem('Озвучка временно недоступна. Текстовый диалог продолжает работать.',true);finish(false)};try{speechEngine.speak(utterance)}catch(e){utterance.onerror?.()}})}
function assessmentClass(value){return({correct:'CORRECT',mostly_correct:'MOSTLY_CORRECT',partial:'PARTIALLY_CORRECT',partially_correct:'PARTIALLY_CORRECT',wrong:'INCORRECT',incorrect:'INCORRECT',insufficient:'PARTIALLY_CORRECT',offtopic:'OFF_TOPIC',off_topic:'OFF_TOPIC'}[normalize(value).replace(/\s/g,'_')]||value)}
async function analyzeAnswer(q,text){const fallback={metrics:evaluate(q,text),classification:classifyAnswer(q,text),assessmentSource:'demo',intent:intentFromText(text)};if(!CFG.aiEndpoint)return fallback;try{const r=await fetch(CFG.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:'assess',mode,topic:{id:topic.id,title:topic.title,points:topic.points},question:{text:q.q,type:q.type,referenceAnswer:q.answer,hint:q.hint,followUp:q.follow},materials:C.questions[topic.id],conversation:sessionHistory.slice(-20),session:sessionContext,studentAnswer:text,rules:{semantic:true,allowParaphrase:true,ignoreFillers:true,labels:['CORRECT','MOSTLY_CORRECT','PARTIALLY_CORRECT','INCORRECT','OFF_TOPIC'],examNoDisclosure:mode==='exam'}})});if(!r.ok)throw Error('ai-assess');const data=await r.json(),classification=assessmentClass(data.classification);if(!['CORRECT','MOSTLY_CORRECT','PARTIALLY_CORRECT','INCORRECT','OFF_TOPIC'].includes(classification))throw Error('ai-schema');return{metrics:data.metrics||fallback.metrics,classification,aiFeedback:data.feedback||null,aiFollowUp:data.followUp||null,assessmentSource:'ai',intent:fallback.intent}}catch(e){setSystem('Смысловая ИИ-проверка недоступна — используется ограниченная демонстрационная оценка.',true);return fallback}}
async function submitSafely(){const text=$('#answerInput').value.trim();if(intentFromText(text)==='repeat'){hardStopSpeechInput();setConversationState('PROCESSING');$('#answerInput').value='';bubble('student',text);sessionHistory.push({role:'user',content:text});const q=sessionContext.lastQuestion;await peterSay(q?`Повторяю вопрос: ${q.q}`:lastPeterText,'ПОВТОР ВОПРОСА');return}if(text){hardStopSpeechInput();setConversationState('PROCESSING')}return submit()}
async function repeatPeter(){if(!lastPeterText)return;hardStopSpeechInput();setConversationState('PROCESSING');const spoken=await speak(lastPeterText);setConversationState('IDLE');if(spoken)scheduleListeningResume()}
async function submit(){const text=$('#answerInput').value.trim();if(!text){setConversationState('IDLE');setSystem('Сначала произнеси или напиши ответ.',true);$('#answerInput').focus();return}$('#answerInput').value='';bubble('student',text);sessionHistory.push({role:'user',content:text});sessionContext.lastAnswer=text;setConversationState('PROCESSING');const intent=intentFromText(text);if(intent==='return'){const previous=sessionContext.previousQuestion;if(previous){revisitQuestion=previous;await peterSay(`Вернёмся. Я спрашивал: ${previous.q}`,'ПРЕДЫДУЩИЙ ВОПРОС')}else await peterSay('Мы только начали эту часть разговора. Ответь на текущий вопрос, а затем сможем к нему вернуться.','КОНТЕКСТ');return}if(intent==='hint'){if(mode==='exam'){await peterSay('В режиме экзамена подсказки недоступны. Ответьте самостоятельно.','ЭКЗАМЕН')}else if(mode==='training'){hint();await peterSay('Дам небольшой ориентир, но не полный ответ. Посмотри на подсказку и попробуй сформулировать мысль самостоятельно.','ПОДСКАЗКА')}else{const reply=await getTutorReply(text);await peterSay(reply,'ОБЪЯСНЕНИЕ')}return}if(mode==='theory'){const reply=await getTutorReply(text);await delay(300);await peterSay(reply,'ОТВЕТ ПО ТЕМЕ');return}if(awaitingFollowUp){pendingAnswer.text+=` ${text}`;Object.assign(pendingAnswer,await analyzeAnswer(pendingAnswer.q,pendingAnswer.text));answers.push(pendingAnswer);awaitingFollowUp=false;const msg=mode==='training'?trainingFeedback(pendingAnswer):examAck();sessionContext.lastFeedback=msg;await peterSay(msg,mode==='training'?'КОРОТКИЙ РАЗБОР':'ЭКЗАМЕН');index++;await delay(280);renderQuestion();return}const q=revisitQuestion||queue[index],item={q,text};Object.assign(item,await analyzeAnswer(q,text));pendingAnswer=item;if(['INCORRECT','PARTIALLY_CORRECT'].includes(item.classification))sessionContext.mistakes.push({question:q.q,answer:text,correct:q.answer,classification:item.classification});if(shouldFollow(item)){awaitingFollowUp=true;await delay(300);await peterSay(item.aiFollowUp||q.follow,mode==='training'?'УТОЧНЯЮЩИЙ ВОПРОС':'УТОЧНЕНИЕ');return}answers.push(item);const msg=mode==='training'?trainingFeedback(item):examAck();sessionContext.lastFeedback=msg;await peterSay(msg,mode==='training'?'КОРОТКИЙ РАЗБОР':'ЭКЗАМЕН');if(revisitQuestion){revisitQuestion=null;await delay(280);await peterSay(`А теперь продолжим с текущим заданием: ${queue[index].q}`,queue[index].type);return}index++;await delay(280);renderQuestion()}
function shouldFollow(item){if(!item.q.follow)return false;return mode==='training'?['MOSTLY_CORRECT','PARTIALLY_CORRECT'].includes(item.classification):mode==='exam'&&item.classification==='PARTIALLY_CORRECT'}
function choose(a,seed=''){return a[Math.abs([...seed].reduce((n,c)=>n+c.charCodeAt(0),0))%a.length]}
function examAck(){return choose(['Ответ принят. Перейдём к следующему заданию.','Хорошо, продолжим.','Ответ зафиксирован. Следующее задание.'],String(index+answers.length))}
function trainingFeedback(item){if(item.aiFeedback)return item.aiFeedback;const c=item.classification;if(c==='CORRECT')return choose(['Да, верно. Продолжим.','Хорошо, ответ принят. Следующий вопрос.','Верно. Давай двигаться дальше.','Да, именно так. Теперь следующий вопрос.','Угу, правильно. Продолжим.'],item.text);if(c==='MOSTLY_CORRECT')return choose([`В целом верно, но здесь не хватает одной важной детали. ${item.q.hint}`,`Ответ почти полный. Уточни ещё один момент: ${item.q.hint}`],item.text);if(c==='PARTIALLY_CORRECT')return choose([`Ты идёшь в правильном направлении. Подумай ещё: ${item.q.hint}`,`Почти. Вспомни ещё одну важную часть ответа: ${item.q.hint}`],item.text);if(item.intent==='dontknow')return`Давай разберёмся. Полного ответа не даю: ${item.q.hint}`;if(c==='OFF_TOPIC')return choose([`Угу, понял тебя. Но давай вернёмся к нашему вопросу: ${item.q.q}`,`Хорошо. А теперь вернёмся к теме, которую мы обсуждали: ${item.q.q}`],item.text);if(hasWrongYear(item.q,item.text)&&normalize(item.text).includes('1812'))return'Не совсем. 1812 год связан уже с Отечественной войной против Наполеона. Подумай о начале XVIII века.';return choose(['Не совсем. Попробуй подумать ещё раз.','Здесь есть ошибка. Давай попробуем разобраться.'],item.text)}
async function getTutorReply(text){if(CFG.aiEndpoint){try{const r=await fetch(CFG.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,topic:{id:topic.id,title:topic.title,points:topic.points},materials:C.questions[topic.id],conversation:sessionHistory.slice(-20),session:sessionContext,message:text})});if(!r.ok)throw Error('ai');const data=await r.json();if(data.reply)return data.reply}catch(e){setSystem('ИИ-репетитор временно недоступен — продолжаем в локальном учебном режиме.',true)}}const low=normalize(text);if(intentFromText(text)==='dontknow'){const q=sessionContext.lastQuestion;return q?`Давай разберёмся вместе. Начни с малого: ${q.hint}`:`Ничего страшного. Выбери один пункт — ${topic.points.slice(0,3).join(', ')} — и я объясню его на примере.`}const found=C.freeAnswers.map(x=>({...x,hits:x.keys.filter(k=>low.includes(normalize(k))).length})).sort((a,b)=>b.hits-a.hits)[0];if(found&&found.hits)return`${found.reply} ${choose(['Хочешь проверить понимание коротким вопросом?','Что из этого разобрать подробнее?','Попробуешь теперь объяснить это своими словами?'],text)}`;const related=C.questions[topic.id].map(q=>({...q,hits:q.keys.filter(k=>low.includes(normalize(k))).length})).sort((a,b)=>b.hits-a.hits)[0];if(related&&related.hits){if(hasWrongYear(related,text)&&low.includes('1812')){sessionContext.mistakes.push({question:related.q,answer:text,correct:related.answer});return'Не совсем. 1812 год связан с Отечественной войной против Наполеона. Полтавская битва произошла значительно раньше — в 1709 году. Попробуешь теперь объяснить, почему эта победа стала переломной?'}return`${related.answer} ${choose([`Проверь себя: ${related.follow}`,'Какая часть ответа требует примера?',`Попробуешь сформулировать итог одним предложением?`],text)}`}sessionContext.offTopicCount++;return choose([`Угу, мысль понял. Давай вернёмся к теме «${topic.title}». Вспомни: ${topic.points[0]} — что здесь было главным?`,`Интересный поворот. Но сейчас нас интересует «${topic.title}». Давай разберём ${topic.points[Math.min(1,topic.points.length-1)]}. Что ты уже об этом знаешь?`,`Хорошо, вернём разговор к нашей теме. Выбери, что обсудим дальше: ${topic.points.slice(0,3).join(', ')}.`],text+sessionContext.offTopicCount)}
function intentFromText(text){const low=normalize(text);if(/повтори.*вопрос|повторите.*вопрос|еще раз.*вопрос/.test(low))return'repeat';if(/(вернемся|вернуться|предыдущ(ий|ему)|тот вопрос|к тому вопросу)/.test(low))return'return';if(/(дай|дайте|нужна|можно|прошу).{0,12}(подсказ|намек)|подскажи|помоги/.test(low))return'hint';if(/не знаю|не понимаю|не помню|затрудняюсь|без понятия/.test(low))return'dontknow';if(/^(да|нет|а почему|почему)$/.test(low))return'context';return'answer'}
function years(value){return [...new Set((String(value).match(/\b(1[6-9]\d{2}|20\d{2})\b/g)||[]))]}
function hasWrongYear(q,text){const expected=years(`${q.answer} ${q.keys.join(' ')}`),given=years(text);return expected.length>0&&given.length>0&&!given.some(y=>expected.includes(y))}
function keyPresent(low,key){const target=normalize(key);if(low.includes(target))return true;const words=low.split(' ');return target.length>=5&&words.some(word=>word.startsWith(target.slice(0,Math.max(4,target.length-2))))}
function meaningHits(q,text){const low=normalize(text);let hits=q.keys.filter(key=>keyPresent(low,key)).length;if(normalize(q.q).includes('полтав')&&low.includes('полтав')&&!q.keys.some(key=>normalize(key).includes('полтав')))hits++;return hits}
function classifyAnswer(q,text){const intent=intentFromText(text);if(intent==='dontknow'||intent==='context')return'INCORRECT';if(intent!=='answer')return'OFF_TOPIC';const hits=meaningHits(q,text);if(hasWrongYear(q,text))return'INCORRECT';const metrics=evaluate(q,text);if(metrics.accuracy>=.82)return'CORRECT';if(metrics.accuracy>=.58)return'MOSTLY_CORRECT';if(hits>0)return'PARTIALLY_CORRECT';const low=normalize(text),topicSignals=C.questions[topic?.id||'war']?.flatMap(x=>x.keys).filter(k=>keyPresent(low,k)).length||0;return topicSignals?'INCORRECT':'OFF_TOPIC'}
function evaluate(q,text){const low=normalize(text),hits=meaningHits(q,text),contradiction=hasWrongYear(q,text),accuracy=contradiction?0:Math.min(1,hits/Math.max(2,Math.ceil(q.keys.length*.65))),words=low.split(/\s+/).filter(Boolean).length,fullness=Math.min(1,words/24),terms=Math.min(1,hits/Math.max(1,q.keys.length)),causality=Math.min(1,(['потому','поэтому','привел','результат','следств','так как','из-за','благодаря'].filter(k=>low.includes(k)).length+accuracy*.45)/2),argument=Math.min(1,(['считаю','однако','но ','с одной','с другой','например','во-первых','вывод'].filter(k=>low.includes(k)).length+fullness*.55)/2);return{accuracy,fullness,terms,causality,argument,contradiction}}
function hint(){const q=revisitQuestion||queue[index];if(!q||mode!=='training')return;sessionContext.hints.push({question:q.q,hint:q.hint});$('#hintBox').innerHTML=`<b>Небольшая подсказка:</b> ${q.hint}`;$('#hintBox').classList.add('show');setSystem('Подсказка не содержит полный ответ.')}
async function ensureMicPermission(){if(!navigator.mediaDevices?.getUserMedia)throw Error('unsupported');if(micStream?.active)return micStream;micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});micEnabled=true;return micStream}
function releaseMic(){micStream?.getTracks().forEach(t=>t.stop());micStream=null}
async function checkMic(){try{await ensureMicPermission();releaseMic();autoListenArmed=true;$('#preMicStatus').textContent='Микрофон разрешён и готов';$('#preMicBtn').classList.add('checked')}catch(e){$('#preMicStatus').textContent=e.name==='NotAllowedError'?'Доступ запрещён в настройках браузера':'Микрофон недоступен';$('#preMicBtn').classList.add('failed')}}
async function startListening(){if(conversationState!=='IDLE'){setSystem(conversationState==='SPEAKING'?'Сначала дождитесь окончания речи Петра.':'Сейчас Пётр обдумывает ответ.',true);return}if(!micEnabled){setSystem('Микрофон выключен. Включи его в окне камеры.',true);return}try{await ensureMicPermission()}catch(e){setSystem(e.name==='NotAllowedError'?'Браузер не дал доступ к микрофону. Нажми значок замка в адресной строке и разреши микрофон.':'Микрофон недоступен. Можно ввести ответ текстом.',true);return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){releaseMic();autoListenArmed=true;const token=++recognitionEpoch,instance=new SR();recognition=instance;instance.lang='ru-RU';instance.interimResults=true;instance.continuous=true;let finalText='';instance.onresult=e=>{if(token!==recognitionEpoch||conversationState!=='LISTENING'||recognition!==instance)return;let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=`${t} `;else interim+=t}$('#answerInput').value=(finalText+interim).trim()};instance.onerror=e=>{if(token!==recognitionEpoch)return;setSystem(e.error==='not-allowed'?'Разреши микрофон в настройках сайта.':`Распознавание остановлено: ${e.error}. Текстовый ввод доступен.`,true);recognition=null;setConversationState('IDLE')};instance.onend=()=>{if(token!==recognitionEpoch)return;recognition=null;releaseMic();if(conversationState==='LISTENING')setConversationState('IDLE')};try{instance.start();setConversationState('LISTENING')}catch(e){recognition=null;setConversationState('IDLE')}return}if(CFG.sttEndpoint&&window.MediaRecorder){autoListenArmed=true;startExternalRecording();return}releaseMic();setConversationState('IDLE');setSystem('В этом браузере нет встроенного распознавания речи. Используй Chrome или Edge либо введи ответ текстом.',true)}
function stopListening(){if(conversationState!=='LISTENING')return;if(recognition){try{recognition.stop()}catch(e){hardStopSpeechInput();setConversationState('IDLE')}return}if(mediaRecorder?.state==='recording'){setConversationState('PROCESSING');mediaRecorder.stop();return}releaseMic();setConversationState('IDLE')}
function listeningUI(on){setConversationState(on?'LISTENING':'IDLE')}
function startExternalRecording(){const token=++recognitionEpoch;audioChunks=[];mediaRecorder=new MediaRecorder(micStream);mediaRecorder.ondataavailable=e=>{if(token===recognitionEpoch)audioChunks.push(e.data)};mediaRecorder.onstart=()=>{if(token===recognitionEpoch)setConversationState('LISTENING')};mediaRecorder.onstop=async()=>{if(token!==recognitionEpoch)return;setConversationState('PROCESSING');try{const fd=new FormData();fd.append('audio',new Blob(audioChunks,{type:mediaRecorder.mimeType}),'answer.webm');const r=await fetch(CFG.sttEndpoint,{method:'POST',body:fd});if(!r.ok)throw Error('stt');const d=await r.json();if(token===recognitionEpoch)$('#answerInput').value=d.text||''}catch(e){setSystem('Сервис распознавания не ответил. Введи ответ текстом.',true)}finally{mediaRecorder=null;releaseMic();if(token===recognitionEpoch)setConversationState('IDLE')}};mediaRecorder.start()}
async function startCamera(){try{if(cameraStream?.active){$('#cameraWindow').classList.remove('hidden');return}cameraStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('#cameraVideo').srcObject=cameraStream;$('#cameraWindow').classList.remove('hidden');$('#preCameraStatus').textContent='Камера включена · запись не ведётся';$('#preCameraBtn').classList.add('checked')}catch(e){$('#preCameraStatus').textContent=e.name==='NotAllowedError'?'Доступ к камере запрещён':'Камера недоступна';setSystem('Камера не включена — она не обязательна.',true)}}
function stopCamera(){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;$('#cameraWindow').classList.add('hidden');$('#preCameraStatus').textContent='Необязательно · видео не записывается'}
function toggleVideo(){videoHidden=!videoHidden;$('#cameraWindow').classList.toggle('video-hidden',videoHidden);$('#hideVideoBtn').textContent=videoHidden?'◌':'◉'}
function toggleMic(){micEnabled=!micEnabled;autoListenArmed=micEnabled&&autoListenArmed;$('#cameraMicToggle').classList.toggle('off',!micEnabled);$('#cameraMicToggle').textContent=micEnabled?'🎙':'🔇';if(!micEnabled)hardStopSpeechInput();setConversationState('IDLE');setSystem(micEnabled?'Микрофон включён. Нажмите «Ответить», чтобы начать слушать.':'Микрофон выключен. Текстовый ввод остаётся доступен.')}
function finishSession(){if(mode==='theory'){goHome();return}autoListenArmed=false;stopListening();stopCamera();cancelPeterSpeech(false);setDidOpen(false);const aggregate=aggregateScores();const total=Math.max(1,Math.round(((aggregate.accuracy*.34)+(aggregate.fullness*.18)+(aggregate.terms*.16)+(aggregate.causality*.17)+(aggregate.argument*.15))*10));$('#totalScore').textContent=total;$('#resultHeadline').textContent=total>=8?'отличный':total>=5?'уверенный':'требует работы';$('#resultMessage').textContent=total>=8?'Ты уверенно владеешь темой и строишь развёрнутые исторические ответы.':total>=5?'Основные знания есть. Добавь больше точных фактов и причинно-следственных связей.':'Повтори ключевые понятия и попробуй ещё раз: теперь у тебя есть подробный разбор.';renderResults(aggregate,total);show('resultsScreen')}
function aggregateScores(){const base={accuracy:0,fullness:0,terms:0,causality:0,argument:0};if(!answers.length)return base;answers.forEach(a=>{if(!a.metrics)a.metrics=evaluate(a.q,a.text);Object.keys(base).forEach(k=>base[k]+=Number(a.metrics[k])||0)});Object.keys(base).forEach(k=>base[k]/=6);return base}
function renderResults(a,total){const names=[['Историческая точность','accuracy'],['Полнота ответа','fullness'],['Термины','terms'],['Причины и следствия','causality'],['Аргументация','argument']];$('#metrics').innerHTML=names.map(([n,k])=>{const v=Math.round(a[k]*100);return`<div class="metric"><span>${n}</span><b>${v}%</b><i style="--value:${v}%"></i></div>`}).join('');const strongest=[...names].sort((x,y)=>a[y[1]]-a[x[1]])[0][0].toLowerCase(),weak=[...names].sort((x,y)=>a[x[1]]-a[y[1]])[0][0].toLowerCase();$('#strengths').innerHTML=listHtml([`Лучше всего: ${strongest}.`,total>=6?'Ты называешь часть ключевых фактов по теме.':'Ты прошёл доступные задания до конца.','Ответы можно формулировать своими словами.']);const misses=answers.filter(x=>x.metrics.accuracy<.5||['wrong','dontknow'].includes(x.classification));$('#errors').innerHTML=listHtml(misses.length?misses.slice(0,3).map(x=>`${x.metrics.contradiction?'Фактическая ошибка':'Неполно раскрыто'}: ${x.q.q}`):['Существенных фактических ошибок локальная проверка не обнаружила.']);$('#repeatTopics').innerHTML=listHtml([`Потренируй: ${weak}.`,...topic.points.slice(0,2)]);$('#reviewList').innerHTML=answers.map((x,i)=>`<details class="review-item"><summary>${i+1}. ${escapeHtml(x.q.q)} · ${Math.round(x.metrics.accuracy*100)}%</summary><p><b>Твой ответ:</b> ${escapeHtml(x.text)}</p><p class="correct"><b>Что следовало сказать:</b> ${escapeHtml(x.q.answer)}</p></details>`).join('')}
function aggregateCurrent(){return answers.length}
function exitRequest(){if(mode==='theory')goHome();else $('#confirmModal').classList.remove('hidden')}
function goHome(){autoListenArmed=false;stopListening();stopCamera();cancelPeterSpeech(false);setDidOpen(false);show('homeScreen')}
function normalize(s){let value=String(s).toLowerCase().replace(/ё/g,'е').replace(/[.,!?;:()«»"']/g,' ').replace(/\b(ээ+|эм+|ну типа|типа|я думаю|мне кажется|вроде бы|вроде)\b/g,' ').replace(/сражени[ея] под полтавой/g,'полтавская битва').replace(/битв[аы] под полтавой/g,'полтавская битва').replace(/шведская армия была разбита/g,'разгром шведской армии').replace(/разбили швед(ов|скую армию)/g,'разгром шведской армии').replace(/преимущество (перешло|получила|получили)/g,'инициатива перешла').replace(/выход к балтике/g,'выход к балтийскому морю');return value.replace(/\s+/g,' ').trim()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function listHtml(a){return a.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
$$('.mode-card').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderTopics()});$$('[data-back]').forEach(b=>b.onclick=goHome);$('#homeBtn').onclick=goHome;$('#setupBack').onclick=renderTopics;$('#startBtn').onclick=begin;$('#sendBtn').onclick=submitSafely;$('#hintBtn').onclick=hint;$('#micBtn').onclick=startListening;$('#stopMicBtn').onclick=stopListening;$('#preMicBtn').onclick=checkMic;$('#repeatBtn').onclick=repeatPeter;$('#stopSpeechBtn').onclick=()=>cancelPeterSpeech(true);$('#preCameraBtn').onclick=startCamera;$('#cameraOff').onclick=stopCamera;$('#hideVideoBtn').onclick=toggleVideo;$('#cameraMicToggle').onclick=toggleMic;$('#finishBtn').onclick=exitRequest;$('#cancelFinish').onclick=()=>$('#confirmModal').classList.add('hidden');$('#confirmFinish').onclick=()=>{$('#confirmModal').classList.add('hidden');finishSession()};$('#voiceToggle').onclick=()=>{voiceOn=!voiceOn;if(!voiceOn)cancelPeterSpeech(false);else if(!didReady)pickRussianVoice();$('#voiceToggle').textContent=voiceOn?'🔊':'🔇';$('#voiceToggle').title=voiceOn?'Голос включён':'Голос выключен';voiceBadge(voiceOn?(didAgent.enabled!==false?(didReady?'D-ID · живой голос и lip-sync':'D-ID Agent · нажмите Start call'):selectedVoice?`Системный резерв · ${selectedVoice.name}`:'Озвучка готова'):'Голос выключен',voiceOn&&didReady)};$('#retryBtn').onclick=()=>selectTopic(topic.id);$('#resultHomeBtn').onclick=goHome;$('#answerInput').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')submitSafely()});
window.addEventListener?.('beforeunload',()=>didSubscriptions.forEach(unsubscribe=>unsubscribe?.()));
window.__HISTORY_TEST__={topics:()=>C.topics.length,questions:()=>Object.values(C.questions).flat().length,evaluate,classifyAnswer,analyzeAnswer,intentFromText,trainingFeedback,examAck,getTutorReply,variedQuestion,startListening,stopListening,peterSay,repeatPeter,cancelPeterSpeech,speakWithDid,initDidAgent,setVoice:on=>{voiceOn=on},setDidApi:api=>{didApi=api;didReady=Boolean(api)},modeFlow:m=>{mode=m;renderTopics();return true},selectTopic,begin,submit:submitSafely,hint,finishSession,checkMic,startCamera,state:()=>({mode,topic:topic?.id,index,answers:answers.length,awaitingFollowUp,hints:sessionContext.hints.length,mistakes:sessionContext.mistakes.length,previousQuestion:sessionContext.previousQuestion?.q,conversationState,recognitionActive:Boolean(recognition),micStreamActive:Boolean(micStream?.active),voiceOn,currentVoice:selectedVoice?.name||null,currentUtterance:Boolean(currentUtterance),didReady,didSpeaking,autoListenArmed})};
})();
